# Golden Brown

$activeBorderColor = rgb(c3a983) rgb(876e48) 45deg
$inactiveBorderColor = rgb(231b0e) rgb(57462c) 45deg

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
    gaps_in = 2
    gaps_out = 4
    border_size = 1
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}

decoration {
    shadow {
        enabled = true
        range = 20
        render_power = 3
        color = rgba(0f0b05ee)
        color_inactive = rgba(0f0b0599)
    }
}

animations {
    enabled = true

    bezier = warmIn,    0.25, 0.1,  0.25, 1.0
    bezier = warmOut,   0.0,  0.0,  0.75, 0.9
    bezier = warmInOut, 0.4,  0.0,  0.6,  1.0
    bezier = gentle,    0.2,  0.0,  0.2,  1.0

    animation = windows,     1, 3,  warmIn,    slide
    animation = windowsOut,  1, 3,  warmOut,   slide
    animation = windowsMove, 1, 3,  warmInOut
    animation = fade,        1, 3,  gentle
    animation = fadeOut,     1, 3,  warmOut
    animation = border,      1, 5,  warmInOut
    animation = borderangle, 1, 90, gentle,    loop
    animation = workspaces,  1, 3,  warmInOut, slidevert
}