background            #0f0b05
foreground            #c3a983

# black
color0  #0f0b05
color8  #57462c

# red
color1  #a88c62
color9  #a88c62

# green
color2  #dec8a7
color10 #dec8a7

# yellow
color3  #dec8a7
color11 #dec8a7

# blue
color4  #c3a983
color12 #c3a983

# magenta
color5  #a88c62
color13 #a88c62

#cyan
color6  #dec8a7
color14 #dec8a7

#white
color7  #c3a983
color15 #231b0e


